---
- hosts: all
  become: true
  tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: latest

    - name: Install Python3
      apt:
        name: python3
        state: latest

    - name: Install Python3 pip
      apt:
        name: python3-pip
        state: latest

    - name: Install OpenSSL
      apt:
        name: openssl
        state: latest

    - name: Create ext4 filesystem on devices
      command: mkfs.ext4 {{ item }}
      with_items:
        - /dev/sdb
        - /dev/sdc
        - /dev/sdd
        - /dev/sde
        - /dev/sdf

    - name: Update /etc/fstab for /dev/sdb
      shell: echo "UUID=$(blkid -s UUID -o value /dev/sdb) /var/lib/mysql ext4 defaults 0 0" >> /etc/fstab

    - name: Update /etc/fstab for /dev/sdc
      shell: echo "UUID=$(blkid -s UUID -o value /dev/sdc) /var/log ext4 defaults 0 0" >> /etc/fstab

    - name: Update /etc/fstab for /dev/sdd
      shell: echo "UUID=$(blkid -s UUID -o value /dev/sdd) /home ext4 defaults 0 0" >> /etc/fstab

    - name: Update /etc/fstab for /dev/sde
      shell: echo "UUID=$(blkid -s UUID -o value /dev/sde) /home/Lime ext4 defaults 0 0" >> /etc/fstab

    - name: Update /etc/fstab for /dev/sdf
      shell: echo "UUID=$(blkid -s UUID -o value /dev/sdf) /home/backup ext4 defaults 0 0" >> /etc/fstab